# Generated by Django 4.1.1 on 2022-10-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_blog_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='snippet',
            field=models.CharField(default='Click on the blog to see more details!', max_length=200),
        ),
    ]
